services:
  back:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    depends_on:
      - posgretdb
    volumes:
      - ./src:/var/www/html/src
      - ./vendor:/var/www/html/vendor
      - ./composer.json:/var/www/html/composer.json
      - ./composer.lock:/var/www/html/composer.lock
      - ./apache.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./.env:/var/www/html/.env
    ports:
      - 4000:80
    command: sh -c "composer install && apache2-foreground"

  posgretdb:
    image: postgres
    restart: no
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
      # - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmind:
    image: dpage/pgadmin4
    restart: no
    ports:
      - 8080:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - posgretdb

volumes:
  pgdata:
